[search]
  enable = false
  type = "fuse"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 300
  highlightTag = "em"
  absoluteURL = false
  [search.algolia]
    index = "en_index"
    appID = "5YGRNRQK1G"
    searchKey = "0ff6874805de24b84aa1d5ebccad56cd"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false
[home]
  rss = 10
  [home.profile]
    enable = true
    avatarURL = "https://i.pinimg.com/564x/9f/63/22/9f6322f645f3901b7dc1f8803c13b83a.jpg"
    title = "d34d"
    subtitle = "Добро пожаловать..."
    typeit = true
    social = true
    disclaimer = ""
  [home.posts]
    enable = true
    paginate = 7
[social]
  GitHub = "0xd34db100d"
  Soundcloud = "euphoriafox"

[header]
    desktopMode = "fixed"
    mobileMode = "auto"
    themeChangeMode = "switch"
    [header.title]
      logo = "https://i.imgur.com/p6ZliNZ.png"
      name = "D34DN37W0RK"
      pre = ""
      post = ""
      typeit = true

[footer]
    enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
    since = 2023

    
[typeit]
    duration = -1
